# Configuration for generating license notices from Cargo package dependencies.
# See https://github.com/EmbarkStudios/cargo-about.
#
# Regenerate license notices with:
#
# ```sh
# cargo about generate about.hbs > license.html
# ```

accepted = ["Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "MIT", "Unicode-3.0"]
